---
- name: Install logstash
  apt: deb=https://download.elastic.co/logstash/logstash/packages/debian/logstash_2.3.1-1_all.deb

- name: Create cert directory
  file: path=/etc/pki/tls/certs state=directory mode=0755

- name: Create private directory
  file: path=/etc/pki/tls/private state=directory mode=0755

- name: Generate certificate
  shell: cd /etc/pki/tls; sudo openssl req -subj '/CN={{ logs_host }}/' -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt

- name: Configure filebeat input
  template: src=./templates/filebeat-input.conf dest=/etc/logstash/conf.d/filebeat-input.conf

- name: Configure syslog filter
  template: src=./templates/syslog-filter.conf dest=/etc/logstash/conf.d/syslog-filter.conf

- name: Configure elasticsearch output
  template: src=./templates/elasticsearch-output.conf dest=/etc/logstash/conf.d/elasticsearch-output.conf

- name: Start logstash
  service: name=logstash state=started
