- hosts: logstash-vagrant
  remote_user: vagrant
  vars_files:
      - variables/logstash/vagrant
  roles:
    - { role: java, sudo: yes }
    - { role: elasticsearch, sudo: yes }
    - { role: kibana, sudo: yes }
    - { role: nginx_kibana, sudo: yes }
    - { role: logstash, sudo: yes }
