---
- stat: path=/var/www/kibana-3.0.1
  register: st

- name: Create kibana directory
  file: path=/var/www/ state=directory mode=0755

- name: Download kibana
  unarchive: src=https://download.elasticsearch.org/kibana/kibana/kibana-3.0.1.tar.gz dest=/var/www/ copy=no
  when: not st.stat.exists

- name: Change port
  replace: dest=/var/www/kibana-3.0.1/config.js regexp='9200' replace='80'

