---
- stat: path=/var/www/kibana-4.5.0
  register: st

- name: Create kibana directory
  file: path=/var/www/ state=directory mode=0755

- name: Install kibana
  apt: deb=https://download.elastic.co/kibana/kibana/kibana_4.5.0_amd64.deb

- name: Start kibana
  service: name=kibana state=started

