---
- name: Install kibana
  apt: deb=https://download.elastic.co/kibana/kibana/kibana_4.5.0_amd64.deb

- name: Configure kibana
  template: src=./templates/kibana.yml dest=/opt/kibana/config/kibana.yml

- name: Start kibana
  service: name=kibana state=started

