---
- name: Install nginx
  apt: name=nginx update_cache=yes

- name: Download kibana config
  get_url: url=https://gist.githubusercontent.com/thisismitch/2205786838a6a5d61f55/raw/f91e06198a7c455925f6e3099e3ea7c186d0b263/nginx.conf dest=/etc/nginx/sites-available/default force=true

- name: Change host
  replace: dest=/etc/nginx/sites-available/default regexp='kibana.myhost.org' replace='localhost'

- name: Change root
  replace: dest=/etc/nginx/sites-available/default regexp='/usr/share/kibana3' replace='/var/www/kibana-3.0.1'

- name: Install apache utils
  apt: name=apache2-utils

- name: install python lib
  action: apt pkg=python-passlib state=latest install_recommends=yes

- name: Set user and password
  htpasswd: path=/etc/nginx/conf.d/kibana.myhost.org.htpasswd name=admin password=123456

- name: Start server
  service: name=nginx state=started

