---
- name: Install nginx
  apt: name=nginx update_cache=yes

- name: Configure nginx
  template: src=./templates/nginx-kibana.conf dest=/etc/nginx/sites-available/default

- name: Install apache utils
  apt: name=apache2-utils

- name: Install python lib
  action: apt pkg=python-passlib state=latest install_recommends=yes

- name: Set user and password
  htpasswd: path=/etc/nginx/conf.d/{{ logs_host }}.htpasswd name={{ kibana_user }} password={{ kibana_password }}

- name: Start server
  service: name=nginx state=started

