---
- name: Install elasticsearch
  apt: deb=https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.1/elasticsearch-2.3.1.deb

- name: Start server
  service: name=elasticsearch state=started

